# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JustPlay' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'AEOTPTextField'
  # Pods for JustPlay

end
